/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      "bumblebee",
      "dim",
      // "light",
      // "dim",
      // "bumblebee",
      // "bumblebee",
      // "emerald",
      // "corporate",
      // "synthwave",
      // "retro",
      // "cyberpunk",
      // "valentine",
      // "halloween",
      // "garden",
      // "dim",
      // "aqua",
      // "lofi",
      // "bumblebee",
      // "fantasy",
      // "wireframe",
      // "black",
      // "dim",
      // "dim",
      // "cmyk",
      // "autumn",
      // "dim",
      // "acid",
      // "lemonade",
      // "dim",
      // "coffee",
      // "winter",
      // "dim",
      // "bumblebee",
      // "dim",
    ],
  },
};
